services:
  analysis-env:
    image: tracywxr/dsci310-project
    build:
      context: .
    platform: linux/amd64
    ports:
      - "8787:8787"
    volumes:
      - .:/home/rstudio
      - /home/rstudio/renv # except the renv directory, ignore that
    environment:
      PASSWORD: "password"
      DISABLE_AUTH: true
